module.exports = {
  apps: [
    {
      name: 'ziwei-server',
      script: './cmd/ziwei-server/main.go',
      interpreter: 'go',
      interpreter_args: 'run',
      cwd: '.',
      env: {
        NODE_ENV: 'development',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      log_file: './logs/ziwei-server.log',
      out_file: './logs/ziwei-server-out.log',
      error_file: './logs/ziwei-server-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'ziwei-web',
      script: 'npm',
      args: 'run dev',
      cwd: './web',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 5000,
      log_file: './logs/ziwei-web.log',
      out_file: './logs/ziwei-web-out.log',
      error_file: './logs/ziwei-web-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      env: {
        NODE_ENV: 'development',
        FORCE_COLOR: '1',
      },
      cron_restart: '0 */2 * * *',
    },
    {
      name: 'ziwei-watchdog',
      script: './scripts/dev-watchdog.js',
      cwd: '.',
      instances: 1,
      autorestart: true,
      watch: false,
      log_file: './logs/ziwei-watchdog.log',
      out_file: './logs/ziwei-watchdog-out.log',
      error_file: './logs/ziwei-watchdog-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      env: {
        NODE_ENV: 'development',
      },
    },
  ],
};
