// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: ziwei.proto

package grpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Hour          int32                  `protobuf:"varint,4,opt,name=hour,proto3" json:"hour,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"` // "male" | "female"
	IsLunar       bool                   `protobuf:"varint,6,opt,name=is_lunar,json=isLunar,proto3" json:"is_lunar,omitempty"`
	IsLeap        bool                   `protobuf:"varint,7,opt,name=is_leap,json=isLeap,proto3" json:"is_leap,omitempty"`
	IsDst         bool                   `protobuf:"varint,8,opt,name=is_dst,json=isDst,proto3" json:"is_dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_ziwei_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CalculateRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CalculateRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *CalculateRequest) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *CalculateRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CalculateRequest) GetIsLunar() bool {
	if x != nil {
		return x.IsLunar
	}
	return false
}

func (x *CalculateRequest) GetIsLeap() bool {
	if x != nil {
		return x.IsLeap
	}
	return false
}

func (x *CalculateRequest) GetIsDst() bool {
	if x != nil {
		return x.IsDst
	}
	return false
}

type CalculateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Gender         string                 `protobuf:"bytes,1,opt,name=gender,proto3" json:"gender,omitempty"`
	Wuxing         string                 `protobuf:"bytes,2,opt,name=wuxing,proto3" json:"wuxing,omitempty"`
	NaYin          string                 `protobuf:"bytes,3,opt,name=na_yin,json=naYin,proto3" json:"na_yin,omitempty"`
	OriginPalace   string                 `protobuf:"bytes,4,opt,name=origin_palace,json=originPalace,proto3" json:"origin_palace,omitempty"`
	MingGong       string                 `protobuf:"bytes,5,opt,name=ming_gong,json=mingGong,proto3" json:"ming_gong,omitempty"`
	ShenGong       string                 `protobuf:"bytes,6,opt,name=shen_gong,json=shenGong,proto3" json:"shen_gong,omitempty"`
	YearPillar     string                 `protobuf:"bytes,7,opt,name=year_pillar,json=yearPillar,proto3" json:"year_pillar,omitempty"`
	DayPillar      string                 `protobuf:"bytes,8,opt,name=day_pillar,json=dayPillar,proto3" json:"day_pillar,omitempty"`
	Palaces        map[string]*PalaceData `protobuf:"bytes,9,rep,name=palaces,proto3" json:"palaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Patterns       []*PatternData         `protobuf:"bytes,10,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Interpretation *InterpretationData    `protobuf:"bytes,11,opt,name=interpretation,proto3" json:"interpretation,omitempty"`
	DaYun          []*DaYunData           `protobuf:"bytes,12,rep,name=da_yun,json=daYun,proto3" json:"da_yun,omitempty"`
	LiuNian        []*TemporalPalaceData  `protobuf:"bytes,13,rep,name=liu_nian,json=liuNian,proto3" json:"liu_nian,omitempty"` // 流年陣列 (1-80歲)
	LiuYue         []*TemporalPalaceData  `protobuf:"bytes,14,rep,name=liu_yue,json=liuYue,proto3" json:"liu_yue,omitempty"`    // 流月陣列 (1-12月)
	LiuRi          []*TemporalPalaceData  `protobuf:"bytes,15,rep,name=liu_ri,json=liuRi,proto3" json:"liu_ri,omitempty"`       // 流日陣列 (1-31日)
	CurrentDaYun   *DaYunData             `protobuf:"bytes,16,opt,name=current_da_yun,json=currentDaYun,proto3" json:"current_da_yun,omitempty"`
	// 流運四化（按宮位分組，用於動態顯示）
	DaYunPalaceTransforms   map[string]*PalaceTransformGroup `protobuf:"bytes,17,rep,name=da_yun_palace_transforms,json=daYunPalaceTransforms,proto3" json:"da_yun_palace_transforms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LiuNianPalaceTransforms map[string]*PalaceTransformGroup `protobuf:"bytes,18,rep,name=liu_nian_palace_transforms,json=liuNianPalaceTransforms,proto3" json:"liu_nian_palace_transforms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LiuYuePalaceTransforms  map[string]*PalaceTransformGroup `protobuf:"bytes,19,rep,name=liu_yue_palace_transforms,json=liuYuePalaceTransforms,proto3" json:"liu_yue_palace_transforms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LiuRiPalaceTransforms   map[string]*PalaceTransformGroup `protobuf:"bytes,20,rep,name=liu_ri_palace_transforms,json=liuRiPalaceTransforms,proto3" json:"liu_ri_palace_transforms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_ziwei_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CalculateResponse) GetWuxing() string {
	if x != nil {
		return x.Wuxing
	}
	return ""
}

func (x *CalculateResponse) GetNaYin() string {
	if x != nil {
		return x.NaYin
	}
	return ""
}

func (x *CalculateResponse) GetOriginPalace() string {
	if x != nil {
		return x.OriginPalace
	}
	return ""
}

func (x *CalculateResponse) GetMingGong() string {
	if x != nil {
		return x.MingGong
	}
	return ""
}

func (x *CalculateResponse) GetShenGong() string {
	if x != nil {
		return x.ShenGong
	}
	return ""
}

func (x *CalculateResponse) GetYearPillar() string {
	if x != nil {
		return x.YearPillar
	}
	return ""
}

func (x *CalculateResponse) GetDayPillar() string {
	if x != nil {
		return x.DayPillar
	}
	return ""
}

func (x *CalculateResponse) GetPalaces() map[string]*PalaceData {
	if x != nil {
		return x.Palaces
	}
	return nil
}

func (x *CalculateResponse) GetPatterns() []*PatternData {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *CalculateResponse) GetInterpretation() *InterpretationData {
	if x != nil {
		return x.Interpretation
	}
	return nil
}

func (x *CalculateResponse) GetDaYun() []*DaYunData {
	if x != nil {
		return x.DaYun
	}
	return nil
}

func (x *CalculateResponse) GetLiuNian() []*TemporalPalaceData {
	if x != nil {
		return x.LiuNian
	}
	return nil
}

func (x *CalculateResponse) GetLiuYue() []*TemporalPalaceData {
	if x != nil {
		return x.LiuYue
	}
	return nil
}

func (x *CalculateResponse) GetLiuRi() []*TemporalPalaceData {
	if x != nil {
		return x.LiuRi
	}
	return nil
}

func (x *CalculateResponse) GetCurrentDaYun() *DaYunData {
	if x != nil {
		return x.CurrentDaYun
	}
	return nil
}

func (x *CalculateResponse) GetDaYunPalaceTransforms() map[string]*PalaceTransformGroup {
	if x != nil {
		return x.DaYunPalaceTransforms
	}
	return nil
}

func (x *CalculateResponse) GetLiuNianPalaceTransforms() map[string]*PalaceTransformGroup {
	if x != nil {
		return x.LiuNianPalaceTransforms
	}
	return nil
}

func (x *CalculateResponse) GetLiuYuePalaceTransforms() map[string]*PalaceTransformGroup {
	if x != nil {
		return x.LiuYuePalaceTransforms
	}
	return nil
}

func (x *CalculateResponse) GetLiuRiPalaceTransforms() map[string]*PalaceTransformGroup {
	if x != nil {
		return x.LiuRiPalaceTransforms
	}
	return nil
}

type PalaceData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Branch            string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	PalaceGan         string                 `protobuf:"bytes,2,opt,name=palace_gan,json=palaceGan,proto3" json:"palace_gan,omitempty"`
	Stars             []string               `protobuf:"bytes,3,rep,name=stars,proto3" json:"stars,omitempty"`
	StarDetails       []*PalaceStar          `protobuf:"bytes,4,rep,name=star_details,json=starDetails,proto3" json:"star_details,omitempty"`
	AssistantStars    []string               `protobuf:"bytes,5,rep,name=assistant_stars,json=assistantStars,proto3" json:"assistant_stars,omitempty"`
	SecondaryStars    []string               `protobuf:"bytes,6,rep,name=secondary_stars,json=secondaryStars,proto3" json:"secondary_stars,omitempty"`
	ChangSheng        string                 `protobuf:"bytes,7,opt,name=chang_sheng,json=changSheng,proto3" json:"chang_sheng,omitempty"`
	BoShi             string                 `protobuf:"bytes,8,opt,name=bo_shi,json=boShi,proto3" json:"bo_shi,omitempty"`
	NatalTransforms   []*TransformData       `protobuf:"bytes,9,rep,name=natal_transforms,json=natalTransforms,proto3" json:"natal_transforms,omitempty"`
	LiuNianStars      []string               `protobuf:"bytes,10,rep,name=liu_nian_stars,json=liuNianStars,proto3" json:"liu_nian_stars,omitempty"`
	LiuNianTransforms []*TransformData       `protobuf:"bytes,11,rep,name=liu_nian_transforms,json=liuNianTransforms,proto3" json:"liu_nian_transforms,omitempty"`
	LiuYueStars       []string               `protobuf:"bytes,12,rep,name=liu_yue_stars,json=liuYueStars,proto3" json:"liu_yue_stars,omitempty"`
	LiuYueTransforms  []*TransformData       `protobuf:"bytes,13,rep,name=liu_yue_transforms,json=liuYueTransforms,proto3" json:"liu_yue_transforms,omitempty"`
	LiuRiStars        []string               `protobuf:"bytes,14,rep,name=liu_ri_stars,json=liuRiStars,proto3" json:"liu_ri_stars,omitempty"`
	LiuRiTransforms   []*TransformData       `protobuf:"bytes,15,rep,name=liu_ri_transforms,json=liuRiTransforms,proto3" json:"liu_ri_transforms,omitempty"`
	DaYunAges         []string               `protobuf:"bytes,16,rep,name=da_yun_ages,json=daYunAges,proto3" json:"da_yun_ages,omitempty"`
	FlyHua            *FlyHuaAnalysis        `protobuf:"bytes,17,opt,name=fly_hua,json=flyHua,proto3" json:"fly_hua,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PalaceData) Reset() {
	*x = PalaceData{}
	mi := &file_ziwei_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PalaceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PalaceData) ProtoMessage() {}

func (x *PalaceData) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PalaceData.ProtoReflect.Descriptor instead.
func (*PalaceData) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{2}
}

func (x *PalaceData) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PalaceData) GetPalaceGan() string {
	if x != nil {
		return x.PalaceGan
	}
	return ""
}

func (x *PalaceData) GetStars() []string {
	if x != nil {
		return x.Stars
	}
	return nil
}

func (x *PalaceData) GetStarDetails() []*PalaceStar {
	if x != nil {
		return x.StarDetails
	}
	return nil
}

func (x *PalaceData) GetAssistantStars() []string {
	if x != nil {
		return x.AssistantStars
	}
	return nil
}

func (x *PalaceData) GetSecondaryStars() []string {
	if x != nil {
		return x.SecondaryStars
	}
	return nil
}

func (x *PalaceData) GetChangSheng() string {
	if x != nil {
		return x.ChangSheng
	}
	return ""
}

func (x *PalaceData) GetBoShi() string {
	if x != nil {
		return x.BoShi
	}
	return ""
}

func (x *PalaceData) GetNatalTransforms() []*TransformData {
	if x != nil {
		return x.NatalTransforms
	}
	return nil
}

func (x *PalaceData) GetLiuNianStars() []string {
	if x != nil {
		return x.LiuNianStars
	}
	return nil
}

func (x *PalaceData) GetLiuNianTransforms() []*TransformData {
	if x != nil {
		return x.LiuNianTransforms
	}
	return nil
}

func (x *PalaceData) GetLiuYueStars() []string {
	if x != nil {
		return x.LiuYueStars
	}
	return nil
}

func (x *PalaceData) GetLiuYueTransforms() []*TransformData {
	if x != nil {
		return x.LiuYueTransforms
	}
	return nil
}

func (x *PalaceData) GetLiuRiStars() []string {
	if x != nil {
		return x.LiuRiStars
	}
	return nil
}

func (x *PalaceData) GetLiuRiTransforms() []*TransformData {
	if x != nil {
		return x.LiuRiTransforms
	}
	return nil
}

func (x *PalaceData) GetDaYunAges() []string {
	if x != nil {
		return x.DaYunAges
	}
	return nil
}

func (x *PalaceData) GetFlyHua() *FlyHuaAnalysis {
	if x != nil {
		return x.FlyHua
	}
	return nil
}

type PalaceStar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Brightness    string                 `protobuf:"bytes,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PalaceStar) Reset() {
	*x = PalaceStar{}
	mi := &file_ziwei_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PalaceStar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PalaceStar) ProtoMessage() {}

func (x *PalaceStar) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PalaceStar.ProtoReflect.Descriptor instead.
func (*PalaceStar) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{3}
}

func (x *PalaceStar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PalaceStar) GetBrightness() string {
	if x != nil {
		return x.Brightness
	}
	return ""
}

type TransformData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Star           string                 `protobuf:"bytes,1,opt,name=star,proto3" json:"star,omitempty"`
	Transformation string                 `protobuf:"bytes,2,opt,name=transformation,proto3" json:"transformation,omitempty"`
	Display        string                 `protobuf:"bytes,3,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransformData) Reset() {
	*x = TransformData{}
	mi := &file_ziwei_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformData) ProtoMessage() {}

func (x *TransformData) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformData.ProtoReflect.Descriptor instead.
func (*TransformData) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{4}
}

func (x *TransformData) GetStar() string {
	if x != nil {
		return x.Star
	}
	return ""
}

func (x *TransformData) GetTransformation() string {
	if x != nil {
		return x.Transformation
	}
	return ""
}

func (x *TransformData) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

type TemporalPalaceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Palace        string                 `protobuf:"bytes,3,opt,name=palace,proto3" json:"palace,omitempty"`
	Stem          string                 `protobuf:"bytes,4,opt,name=stem,proto3" json:"stem,omitempty"`
	TimeBranch    string                 `protobuf:"bytes,5,opt,name=time_branch,json=timeBranch,proto3" json:"time_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalPalaceData) Reset() {
	*x = TemporalPalaceData{}
	mi := &file_ziwei_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalPalaceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalPalaceData) ProtoMessage() {}

func (x *TemporalPalaceData) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalPalaceData.ProtoReflect.Descriptor instead.
func (*TemporalPalaceData) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{5}
}

func (x *TemporalPalaceData) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TemporalPalaceData) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *TemporalPalaceData) GetPalace() string {
	if x != nil {
		return x.Palace
	}
	return ""
}

func (x *TemporalPalaceData) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *TemporalPalaceData) GetTimeBranch() string {
	if x != nil {
		return x.TimeBranch
	}
	return ""
}

// 宮位四化組（用於 map 的 wrapper）
type PalaceTransformGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transforms    []*TransformData       `protobuf:"bytes,1,rep,name=transforms,proto3" json:"transforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PalaceTransformGroup) Reset() {
	*x = PalaceTransformGroup{}
	mi := &file_ziwei_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PalaceTransformGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PalaceTransformGroup) ProtoMessage() {}

func (x *PalaceTransformGroup) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PalaceTransformGroup.ProtoReflect.Descriptor instead.
func (*PalaceTransformGroup) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{6}
}

func (x *PalaceTransformGroup) GetTransforms() []*TransformData {
	if x != nil {
		return x.Transforms
	}
	return nil
}

type DaYunData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	StartAge      int32                  `protobuf:"varint,2,opt,name=start_age,json=startAge,proto3" json:"start_age,omitempty"`
	EndAge        int32                  `protobuf:"varint,3,opt,name=end_age,json=endAge,proto3" json:"end_age,omitempty"`
	Stem          string                 `protobuf:"bytes,4,opt,name=stem,proto3" json:"stem,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	Palace        string                 `protobuf:"bytes,6,opt,name=palace,proto3" json:"palace,omitempty"`
	Transforms    []*TransformData       `protobuf:"bytes,7,rep,name=transforms,proto3" json:"transforms,omitempty"` // 大限四化
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaYunData) Reset() {
	*x = DaYunData{}
	mi := &file_ziwei_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaYunData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaYunData) ProtoMessage() {}

func (x *DaYunData) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaYunData.ProtoReflect.Descriptor instead.
func (*DaYunData) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{7}
}

func (x *DaYunData) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DaYunData) GetStartAge() int32 {
	if x != nil {
		return x.StartAge
	}
	return 0
}

func (x *DaYunData) GetEndAge() int32 {
	if x != nil {
		return x.EndAge
	}
	return 0
}

func (x *DaYunData) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *DaYunData) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *DaYunData) GetPalace() string {
	if x != nil {
		return x.Palace
	}
	return ""
}

func (x *DaYunData) GetTransforms() []*TransformData {
	if x != nil {
		return x.Transforms
	}
	return nil
}

type PatternData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatternData) Reset() {
	*x = PatternData{}
	mi := &file_ziwei_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatternData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatternData) ProtoMessage() {}

func (x *PatternData) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatternData.ProtoReflect.Descriptor instead.
func (*PatternData) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{8}
}

func (x *PatternData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatternData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PatternData) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type InterpretationData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Summary              string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	CharacterTraits      string                 `protobuf:"bytes,2,opt,name=character_traits,json=characterTraits,proto3" json:"character_traits,omitempty"`
	OriginPalaceAnalysis string                 `protobuf:"bytes,3,opt,name=origin_palace_analysis,json=originPalaceAnalysis,proto3" json:"origin_palace_analysis,omitempty"`
	KarmicNarrative      []*KarmicStep          `protobuf:"bytes,4,rep,name=karmic_narrative,json=karmicNarrative,proto3" json:"karmic_narrative,omitempty"`
	SanFangDiagnosis     []*SanFangRole         `protobuf:"bytes,5,rep,name=san_fang_diagnosis,json=sanFangDiagnosis,proto3" json:"san_fang_diagnosis,omitempty"`
	StarDetails          []*DeepStarAnalysis    `protobuf:"bytes,6,rep,name=star_details,json=starDetails,proto3" json:"star_details,omitempty"`
	OriginFlyHua         *FlyHuaAnalysis        `protobuf:"bytes,7,opt,name=origin_fly_hua,json=originFlyHua,proto3" json:"origin_fly_hua,omitempty"`
	TemporalResonance    []*ResonancePoint      `protobuf:"bytes,8,rep,name=temporal_resonance,json=temporalResonance,proto3" json:"temporal_resonance,omitempty"`
	ClassicPatterns      []string               `protobuf:"bytes,9,rep,name=classic_patterns,json=classicPatterns,proto3" json:"classic_patterns,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InterpretationData) Reset() {
	*x = InterpretationData{}
	mi := &file_ziwei_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterpretationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterpretationData) ProtoMessage() {}

func (x *InterpretationData) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterpretationData.ProtoReflect.Descriptor instead.
func (*InterpretationData) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{9}
}

func (x *InterpretationData) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *InterpretationData) GetCharacterTraits() string {
	if x != nil {
		return x.CharacterTraits
	}
	return ""
}

func (x *InterpretationData) GetOriginPalaceAnalysis() string {
	if x != nil {
		return x.OriginPalaceAnalysis
	}
	return ""
}

func (x *InterpretationData) GetKarmicNarrative() []*KarmicStep {
	if x != nil {
		return x.KarmicNarrative
	}
	return nil
}

func (x *InterpretationData) GetSanFangDiagnosis() []*SanFangRole {
	if x != nil {
		return x.SanFangDiagnosis
	}
	return nil
}

func (x *InterpretationData) GetStarDetails() []*DeepStarAnalysis {
	if x != nil {
		return x.StarDetails
	}
	return nil
}

func (x *InterpretationData) GetOriginFlyHua() *FlyHuaAnalysis {
	if x != nil {
		return x.OriginFlyHua
	}
	return nil
}

func (x *InterpretationData) GetTemporalResonance() []*ResonancePoint {
	if x != nil {
		return x.TemporalResonance
	}
	return nil
}

func (x *InterpretationData) GetClassicPatterns() []string {
	if x != nil {
		return x.ClassicPatterns
	}
	return nil
}

type DeepStarAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Verse         string                 `protobuf:"bytes,2,opt,name=verse,proto3" json:"verse,omitempty"`
	Positive      string                 `protobuf:"bytes,3,opt,name=positive,proto3" json:"positive,omitempty"`
	Negative      string                 `protobuf:"bytes,4,opt,name=negative,proto3" json:"negative,omitempty"`
	Remedy        string                 `protobuf:"bytes,5,opt,name=remedy,proto3" json:"remedy,omitempty"`
	Evolution     string                 `protobuf:"bytes,6,opt,name=evolution,proto3" json:"evolution,omitempty"`
	Brightness    string                 `protobuf:"bytes,7,opt,name=brightness,proto3" json:"brightness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepStarAnalysis) Reset() {
	*x = DeepStarAnalysis{}
	mi := &file_ziwei_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepStarAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepStarAnalysis) ProtoMessage() {}

func (x *DeepStarAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepStarAnalysis.ProtoReflect.Descriptor instead.
func (*DeepStarAnalysis) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{10}
}

func (x *DeepStarAnalysis) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeepStarAnalysis) GetVerse() string {
	if x != nil {
		return x.Verse
	}
	return ""
}

func (x *DeepStarAnalysis) GetPositive() string {
	if x != nil {
		return x.Positive
	}
	return ""
}

func (x *DeepStarAnalysis) GetNegative() string {
	if x != nil {
		return x.Negative
	}
	return ""
}

func (x *DeepStarAnalysis) GetRemedy() string {
	if x != nil {
		return x.Remedy
	}
	return ""
}

func (x *DeepStarAnalysis) GetEvolution() string {
	if x != nil {
		return x.Evolution
	}
	return ""
}

func (x *DeepStarAnalysis) GetBrightness() string {
	if x != nil {
		return x.Brightness
	}
	return ""
}

type FlyHuaAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPalace    string                 `protobuf:"bytes,1,opt,name=from_palace,json=fromPalace,proto3" json:"from_palace,omitempty"`
	Stem          string                 `protobuf:"bytes,2,opt,name=stem,proto3" json:"stem,omitempty"`
	Stages        []*FlyStage            `protobuf:"bytes,3,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlyHuaAnalysis) Reset() {
	*x = FlyHuaAnalysis{}
	mi := &file_ziwei_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlyHuaAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlyHuaAnalysis) ProtoMessage() {}

func (x *FlyHuaAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlyHuaAnalysis.ProtoReflect.Descriptor instead.
func (*FlyHuaAnalysis) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{11}
}

func (x *FlyHuaAnalysis) GetFromPalace() string {
	if x != nil {
		return x.FromPalace
	}
	return ""
}

func (x *FlyHuaAnalysis) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *FlyHuaAnalysis) GetStages() []*FlyStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type FlyStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Star          string                 `protobuf:"bytes,2,opt,name=star,proto3" json:"star,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Motive        string                 `protobuf:"bytes,4,opt,name=motive,proto3" json:"motive,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Trap          string                 `protobuf:"bytes,6,opt,name=trap,proto3" json:"trap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlyStage) Reset() {
	*x = FlyStage{}
	mi := &file_ziwei_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlyStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlyStage) ProtoMessage() {}

func (x *FlyStage) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlyStage.ProtoReflect.Descriptor instead.
func (*FlyStage) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{12}
}

func (x *FlyStage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlyStage) GetStar() string {
	if x != nil {
		return x.Star
	}
	return ""
}

func (x *FlyStage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FlyStage) GetMotive() string {
	if x != nil {
		return x.Motive
	}
	return ""
}

func (x *FlyStage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FlyStage) GetTrap() string {
	if x != nil {
		return x.Trap
	}
	return ""
}

type ResonancePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         string                 `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Star          string                 `protobuf:"bytes,3,opt,name=star,proto3" json:"star,omitempty"`
	Natal         string                 `protobuf:"bytes,4,opt,name=natal,proto3" json:"natal,omitempty"`
	Palace        string                 `protobuf:"bytes,5,opt,name=palace,proto3" json:"palace,omitempty"`
	Mood          string                 `protobuf:"bytes,6,opt,name=mood,proto3" json:"mood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResonancePoint) Reset() {
	*x = ResonancePoint{}
	mi := &file_ziwei_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResonancePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResonancePoint) ProtoMessage() {}

func (x *ResonancePoint) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResonancePoint.ProtoReflect.Descriptor instead.
func (*ResonancePoint) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{13}
}

func (x *ResonancePoint) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *ResonancePoint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResonancePoint) GetStar() string {
	if x != nil {
		return x.Star
	}
	return ""
}

func (x *ResonancePoint) GetNatal() string {
	if x != nil {
		return x.Natal
	}
	return ""
}

func (x *ResonancePoint) GetPalace() string {
	if x != nil {
		return x.Palace
	}
	return ""
}

func (x *ResonancePoint) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

type KarmicStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Star          string                 `protobuf:"bytes,3,opt,name=star,proto3" json:"star,omitempty"`
	Palace        string                 `protobuf:"bytes,4,opt,name=palace,proto3" json:"palace,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KarmicStep) Reset() {
	*x = KarmicStep{}
	mi := &file_ziwei_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KarmicStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarmicStep) ProtoMessage() {}

func (x *KarmicStep) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarmicStep.ProtoReflect.Descriptor instead.
func (*KarmicStep) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{14}
}

func (x *KarmicStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KarmicStep) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *KarmicStep) GetStar() string {
	if x != nil {
		return x.Star
	}
	return ""
}

func (x *KarmicStep) GetPalace() string {
	if x != nil {
		return x.Palace
	}
	return ""
}

func (x *KarmicStep) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type SanFangRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Palace        string                 `protobuf:"bytes,2,opt,name=palace,proto3" json:"palace,omitempty"`
	Diagnosis     string                 `protobuf:"bytes,3,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanFangRole) Reset() {
	*x = SanFangRole{}
	mi := &file_ziwei_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanFangRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanFangRole) ProtoMessage() {}

func (x *SanFangRole) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanFangRole.ProtoReflect.Descriptor instead.
func (*SanFangRole) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{15}
}

func (x *SanFangRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SanFangRole) GetPalace() string {
	if x != nil {
		return x.Palace
	}
	return ""
}

func (x *SanFangRole) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

type BirthRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,5,opt,name=day,proto3" json:"day,omitempty"`
	Hour          int32                  `protobuf:"varint,6,opt,name=hour,proto3" json:"hour,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	IsLunar       bool                   `protobuf:"varint,8,opt,name=is_lunar,json=isLunar,proto3" json:"is_lunar,omitempty"`
	IsLeap        bool                   `protobuf:"varint,9,opt,name=is_leap,json=isLeap,proto3" json:"is_leap,omitempty"`
	IsDst         bool                   `protobuf:"varint,10,opt,name=is_dst,json=isDst,proto3" json:"is_dst,omitempty"`
	Tags          []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BirthRecord) Reset() {
	*x = BirthRecord{}
	mi := &file_ziwei_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BirthRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirthRecord) ProtoMessage() {}

func (x *BirthRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirthRecord.ProtoReflect.Descriptor instead.
func (*BirthRecord) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{16}
}

func (x *BirthRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BirthRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BirthRecord) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BirthRecord) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *BirthRecord) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *BirthRecord) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *BirthRecord) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *BirthRecord) GetIsLunar() bool {
	if x != nil {
		return x.IsLunar
	}
	return false
}

func (x *BirthRecord) GetIsLeap() bool {
	if x != nil {
		return x.IsLeap
	}
	return false
}

func (x *BirthRecord) GetIsDst() bool {
	if x != nil {
		return x.IsDst
	}
	return false
}

func (x *BirthRecord) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BirthRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_ziwei_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{17}
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*BirthRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_ziwei_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{18}
}

func (x *ListRecordsResponse) GetRecords() []*BirthRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,4,opt,name=day,proto3" json:"day,omitempty"`
	Hour          int32                  `protobuf:"varint,5,opt,name=hour,proto3" json:"hour,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	IsLunar       bool                   `protobuf:"varint,7,opt,name=is_lunar,json=isLunar,proto3" json:"is_lunar,omitempty"`
	IsLeap        bool                   `protobuf:"varint,8,opt,name=is_leap,json=isLeap,proto3" json:"is_leap,omitempty"`
	IsDst         bool                   `protobuf:"varint,9,opt,name=is_dst,json=isDst,proto3" json:"is_dst,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_ziwei_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{19}
}

func (x *CreateRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRecordRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateRecordRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CreateRecordRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *CreateRecordRequest) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *CreateRecordRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateRecordRequest) GetIsLunar() bool {
	if x != nil {
		return x.IsLunar
	}
	return false
}

func (x *CreateRecordRequest) GetIsLeap() bool {
	if x != nil {
		return x.IsLeap
	}
	return false
}

func (x *CreateRecordRequest) GetIsDst() bool {
	if x != nil {
		return x.IsDst
	}
	return false
}

func (x *CreateRecordRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *BirthRecord           `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordResponse) Reset() {
	*x = CreateRecordResponse{}
	mi := &file_ziwei_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResponse) ProtoMessage() {}

func (x *CreateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateRecordResponse) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{20}
}

func (x *CreateRecordResponse) GetRecord() *BirthRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_ziwei_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_ziwei_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordResponse) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_ziwei_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{23}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_ziwei_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{24}
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_ziwei_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziwei_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_ziwei_proto_rawDescGZIP(), []int{25}
}

func (x *ListTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_ziwei_proto protoreflect.FileDescriptor

const file_ziwei_proto_rawDesc = "" +
	"\n" +
	"\vziwei.proto\x12\bziwei.v1\"\xc5\x01\n" +
	"\x10CalculateRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\x12\x12\n" +
	"\x04hour\x18\x04 \x01(\x05R\x04hour\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x19\n" +
	"\bis_lunar\x18\x06 \x01(\bR\aisLunar\x12\x17\n" +
	"\ais_leap\x18\a \x01(\bR\x06isLeap\x12\x15\n" +
	"\x06is_dst\x18\b \x01(\bR\x05isDst\"\x8c\r\n" +
	"\x11CalculateResponse\x12\x16\n" +
	"\x06gender\x18\x01 \x01(\tR\x06gender\x12\x16\n" +
	"\x06wuxing\x18\x02 \x01(\tR\x06wuxing\x12\x15\n" +
	"\x06na_yin\x18\x03 \x01(\tR\x05naYin\x12#\n" +
	"\rorigin_palace\x18\x04 \x01(\tR\foriginPalace\x12\x1b\n" +
	"\tming_gong\x18\x05 \x01(\tR\bmingGong\x12\x1b\n" +
	"\tshen_gong\x18\x06 \x01(\tR\bshenGong\x12\x1f\n" +
	"\vyear_pillar\x18\a \x01(\tR\n" +
	"yearPillar\x12\x1d\n" +
	"\n" +
	"day_pillar\x18\b \x01(\tR\tdayPillar\x12B\n" +
	"\apalaces\x18\t \x03(\v2(.ziwei.v1.CalculateResponse.PalacesEntryR\apalaces\x121\n" +
	"\bpatterns\x18\n" +
	" \x03(\v2\x15.ziwei.v1.PatternDataR\bpatterns\x12D\n" +
	"\x0einterpretation\x18\v \x01(\v2\x1c.ziwei.v1.InterpretationDataR\x0einterpretation\x12*\n" +
	"\x06da_yun\x18\f \x03(\v2\x13.ziwei.v1.DaYunDataR\x05daYun\x127\n" +
	"\bliu_nian\x18\r \x03(\v2\x1c.ziwei.v1.TemporalPalaceDataR\aliuNian\x125\n" +
	"\aliu_yue\x18\x0e \x03(\v2\x1c.ziwei.v1.TemporalPalaceDataR\x06liuYue\x123\n" +
	"\x06liu_ri\x18\x0f \x03(\v2\x1c.ziwei.v1.TemporalPalaceDataR\x05liuRi\x129\n" +
	"\x0ecurrent_da_yun\x18\x10 \x01(\v2\x13.ziwei.v1.DaYunDataR\fcurrentDaYun\x12o\n" +
	"\x18da_yun_palace_transforms\x18\x11 \x03(\v26.ziwei.v1.CalculateResponse.DaYunPalaceTransformsEntryR\x15daYunPalaceTransforms\x12u\n" +
	"\x1aliu_nian_palace_transforms\x18\x12 \x03(\v28.ziwei.v1.CalculateResponse.LiuNianPalaceTransformsEntryR\x17liuNianPalaceTransforms\x12r\n" +
	"\x19liu_yue_palace_transforms\x18\x13 \x03(\v27.ziwei.v1.CalculateResponse.LiuYuePalaceTransformsEntryR\x16liuYuePalaceTransforms\x12o\n" +
	"\x18liu_ri_palace_transforms\x18\x14 \x03(\v26.ziwei.v1.CalculateResponse.LiuRiPalaceTransformsEntryR\x15liuRiPalaceTransforms\x1aP\n" +
	"\fPalacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.ziwei.v1.PalaceDataR\x05value:\x028\x01\x1ah\n" +
	"\x1aDaYunPalaceTransformsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.ziwei.v1.PalaceTransformGroupR\x05value:\x028\x01\x1aj\n" +
	"\x1cLiuNianPalaceTransformsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.ziwei.v1.PalaceTransformGroupR\x05value:\x028\x01\x1ai\n" +
	"\x1bLiuYuePalaceTransformsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.ziwei.v1.PalaceTransformGroupR\x05value:\x028\x01\x1ah\n" +
	"\x1aLiuRiPalaceTransformsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.ziwei.v1.PalaceTransformGroupR\x05value:\x028\x01\"\xf4\x05\n" +
	"\n" +
	"PalaceData\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"palace_gan\x18\x02 \x01(\tR\tpalaceGan\x12\x14\n" +
	"\x05stars\x18\x03 \x03(\tR\x05stars\x127\n" +
	"\fstar_details\x18\x04 \x03(\v2\x14.ziwei.v1.PalaceStarR\vstarDetails\x12'\n" +
	"\x0fassistant_stars\x18\x05 \x03(\tR\x0eassistantStars\x12'\n" +
	"\x0fsecondary_stars\x18\x06 \x03(\tR\x0esecondaryStars\x12\x1f\n" +
	"\vchang_sheng\x18\a \x01(\tR\n" +
	"changSheng\x12\x15\n" +
	"\x06bo_shi\x18\b \x01(\tR\x05boShi\x12B\n" +
	"\x10natal_transforms\x18\t \x03(\v2\x17.ziwei.v1.TransformDataR\x0fnatalTransforms\x12$\n" +
	"\x0eliu_nian_stars\x18\n" +
	" \x03(\tR\fliuNianStars\x12G\n" +
	"\x13liu_nian_transforms\x18\v \x03(\v2\x17.ziwei.v1.TransformDataR\x11liuNianTransforms\x12\"\n" +
	"\rliu_yue_stars\x18\f \x03(\tR\vliuYueStars\x12E\n" +
	"\x12liu_yue_transforms\x18\r \x03(\v2\x17.ziwei.v1.TransformDataR\x10liuYueTransforms\x12 \n" +
	"\fliu_ri_stars\x18\x0e \x03(\tR\n" +
	"liuRiStars\x12C\n" +
	"\x11liu_ri_transforms\x18\x0f \x03(\v2\x17.ziwei.v1.TransformDataR\x0fliuRiTransforms\x12\x1e\n" +
	"\vda_yun_ages\x18\x10 \x03(\tR\tdaYunAges\x121\n" +
	"\afly_hua\x18\x11 \x01(\v2\x18.ziwei.v1.FlyHuaAnalysisR\x06flyHua\"@\n" +
	"\n" +
	"PalaceStar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"brightness\x18\x02 \x01(\tR\n" +
	"brightness\"e\n" +
	"\rTransformData\x12\x12\n" +
	"\x04star\x18\x01 \x01(\tR\x04star\x12&\n" +
	"\x0etransformation\x18\x02 \x01(\tR\x0etransformation\x12\x18\n" +
	"\adisplay\x18\x03 \x01(\tR\adisplay\"\x8f\x01\n" +
	"\x12TemporalPalaceData\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x16\n" +
	"\x06palace\x18\x03 \x01(\tR\x06palace\x12\x12\n" +
	"\x04stem\x18\x04 \x01(\tR\x04stem\x12\x1f\n" +
	"\vtime_branch\x18\x05 \x01(\tR\n" +
	"timeBranch\"O\n" +
	"\x14PalaceTransformGroup\x127\n" +
	"\n" +
	"transforms\x18\x01 \x03(\v2\x17.ziwei.v1.TransformDataR\n" +
	"transforms\"\xd4\x01\n" +
	"\tDaYunData\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x1b\n" +
	"\tstart_age\x18\x02 \x01(\x05R\bstartAge\x12\x17\n" +
	"\aend_age\x18\x03 \x01(\x05R\x06endAge\x12\x12\n" +
	"\x04stem\x18\x04 \x01(\tR\x04stem\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x16\n" +
	"\x06palace\x18\x06 \x01(\tR\x06palace\x127\n" +
	"\n" +
	"transforms\x18\a \x03(\v2\x17.ziwei.v1.TransformDataR\n" +
	"transforms\"Y\n" +
	"\vPatternData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\"\x88\x04\n" +
	"\x12InterpretationData\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12)\n" +
	"\x10character_traits\x18\x02 \x01(\tR\x0fcharacterTraits\x124\n" +
	"\x16origin_palace_analysis\x18\x03 \x01(\tR\x14originPalaceAnalysis\x12?\n" +
	"\x10karmic_narrative\x18\x04 \x03(\v2\x14.ziwei.v1.KarmicStepR\x0fkarmicNarrative\x12C\n" +
	"\x12san_fang_diagnosis\x18\x05 \x03(\v2\x15.ziwei.v1.SanFangRoleR\x10sanFangDiagnosis\x12=\n" +
	"\fstar_details\x18\x06 \x03(\v2\x1a.ziwei.v1.DeepStarAnalysisR\vstarDetails\x12>\n" +
	"\x0eorigin_fly_hua\x18\a \x01(\v2\x18.ziwei.v1.FlyHuaAnalysisR\foriginFlyHua\x12G\n" +
	"\x12temporal_resonance\x18\b \x03(\v2\x18.ziwei.v1.ResonancePointR\x11temporalResonance\x12)\n" +
	"\x10classic_patterns\x18\t \x03(\tR\x0fclassicPatterns\"\xca\x01\n" +
	"\x10DeepStarAnalysis\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05verse\x18\x02 \x01(\tR\x05verse\x12\x1a\n" +
	"\bpositive\x18\x03 \x01(\tR\bpositive\x12\x1a\n" +
	"\bnegative\x18\x04 \x01(\tR\bnegative\x12\x16\n" +
	"\x06remedy\x18\x05 \x01(\tR\x06remedy\x12\x1c\n" +
	"\tevolution\x18\x06 \x01(\tR\tevolution\x12\x1e\n" +
	"\n" +
	"brightness\x18\a \x01(\tR\n" +
	"brightness\"q\n" +
	"\x0eFlyHuaAnalysis\x12\x1f\n" +
	"\vfrom_palace\x18\x01 \x01(\tR\n" +
	"fromPalace\x12\x12\n" +
	"\x04stem\x18\x02 \x01(\tR\x04stem\x12*\n" +
	"\x06stages\x18\x03 \x03(\v2\x12.ziwei.v1.FlyStageR\x06stages\"\x8e\x01\n" +
	"\bFlyStage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04star\x18\x02 \x01(\tR\x04star\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06motive\x18\x04 \x01(\tR\x06motive\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x12\n" +
	"\x04trap\x18\x06 \x01(\tR\x04trap\"\x90\x01\n" +
	"\x0eResonancePoint\x12\x14\n" +
	"\x05layer\x18\x01 \x01(\tR\x05layer\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04star\x18\x03 \x01(\tR\x04star\x12\x14\n" +
	"\x05natal\x18\x04 \x01(\tR\x05natal\x12\x16\n" +
	"\x06palace\x18\x05 \x01(\tR\x06palace\x12\x12\n" +
	"\x04mood\x18\x06 \x01(\tR\x04mood\"t\n" +
	"\n" +
	"KarmicStep\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04star\x18\x03 \x01(\tR\x04star\x12\x16\n" +
	"\x06palace\x18\x04 \x01(\tR\x06palace\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\"W\n" +
	"\vSanFangRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x16\n" +
	"\x06palace\x18\x02 \x01(\tR\x06palace\x12\x1c\n" +
	"\tdiagnosis\x18\x03 \x01(\tR\tdiagnosis\"\x97\x02\n" +
	"\vBirthRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x04 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x05 \x01(\x05R\x03day\x12\x12\n" +
	"\x04hour\x18\x06 \x01(\x05R\x04hour\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12\x19\n" +
	"\bis_lunar\x18\b \x01(\bR\aisLunar\x12\x17\n" +
	"\ais_leap\x18\t \x01(\bR\x06isLeap\x12\x15\n" +
	"\x06is_dst\x18\n" +
	" \x01(\bR\x05isDst\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\x14\n" +
	"\x12ListRecordsRequest\"F\n" +
	"\x13ListRecordsResponse\x12/\n" +
	"\arecords\x18\x01 \x03(\v2\x15.ziwei.v1.BirthRecordR\arecords\"\xf0\x01\n" +
	"\x13CreateRecordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x04 \x01(\x05R\x03day\x12\x12\n" +
	"\x04hour\x18\x05 \x01(\x05R\x04hour\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x19\n" +
	"\bis_lunar\x18\a \x01(\bR\aisLunar\x12\x17\n" +
	"\ais_leap\x18\b \x01(\bR\x06isLeap\x12\x15\n" +
	"\x06is_dst\x18\t \x01(\bR\x05isDst\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\"E\n" +
	"\x14CreateRecordResponse\x12-\n" +
	"\x06record\x18\x01 \x01(\v2\x15.ziwei.v1.BirthRecordR\x06record\"%\n" +
	"\x13DeleteRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"\x11\n" +
	"\x0fListTagsRequest\"5\n" +
	"\x10ListTagsResponse\x12!\n" +
	"\x04tags\x18\x01 \x03(\v2\r.ziwei.v1.TagR\x04tags2\x81\x03\n" +
	"\fZiweiService\x12D\n" +
	"\tCalculate\x12\x1a.ziwei.v1.CalculateRequest\x1a\x1b.ziwei.v1.CalculateResponse\x12J\n" +
	"\vListRecords\x12\x1c.ziwei.v1.ListRecordsRequest\x1a\x1d.ziwei.v1.ListRecordsResponse\x12M\n" +
	"\fCreateRecord\x12\x1d.ziwei.v1.CreateRecordRequest\x1a\x1e.ziwei.v1.CreateRecordResponse\x12M\n" +
	"\fDeleteRecord\x12\x1d.ziwei.v1.DeleteRecordRequest\x1a\x1e.ziwei.v1.DeleteRecordResponse\x12A\n" +
	"\bListTags\x12\x19.ziwei.v1.ListTagsRequest\x1a\x1a.ziwei.v1.ListTagsResponseB9Z7github.com/kaecer68/ziwei-zenith/pkg/api/grpc/v1;grpcv1b\x06proto3"

var (
	file_ziwei_proto_rawDescOnce sync.Once
	file_ziwei_proto_rawDescData []byte
)

func file_ziwei_proto_rawDescGZIP() []byte {
	file_ziwei_proto_rawDescOnce.Do(func() {
		file_ziwei_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ziwei_proto_rawDesc), len(file_ziwei_proto_rawDesc)))
	})
	return file_ziwei_proto_rawDescData
}

var file_ziwei_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_ziwei_proto_goTypes = []any{
	(*CalculateRequest)(nil),     // 0: ziwei.v1.CalculateRequest
	(*CalculateResponse)(nil),    // 1: ziwei.v1.CalculateResponse
	(*PalaceData)(nil),           // 2: ziwei.v1.PalaceData
	(*PalaceStar)(nil),           // 3: ziwei.v1.PalaceStar
	(*TransformData)(nil),        // 4: ziwei.v1.TransformData
	(*TemporalPalaceData)(nil),   // 5: ziwei.v1.TemporalPalaceData
	(*PalaceTransformGroup)(nil), // 6: ziwei.v1.PalaceTransformGroup
	(*DaYunData)(nil),            // 7: ziwei.v1.DaYunData
	(*PatternData)(nil),          // 8: ziwei.v1.PatternData
	(*InterpretationData)(nil),   // 9: ziwei.v1.InterpretationData
	(*DeepStarAnalysis)(nil),     // 10: ziwei.v1.DeepStarAnalysis
	(*FlyHuaAnalysis)(nil),       // 11: ziwei.v1.FlyHuaAnalysis
	(*FlyStage)(nil),             // 12: ziwei.v1.FlyStage
	(*ResonancePoint)(nil),       // 13: ziwei.v1.ResonancePoint
	(*KarmicStep)(nil),           // 14: ziwei.v1.KarmicStep
	(*SanFangRole)(nil),          // 15: ziwei.v1.SanFangRole
	(*BirthRecord)(nil),          // 16: ziwei.v1.BirthRecord
	(*ListRecordsRequest)(nil),   // 17: ziwei.v1.ListRecordsRequest
	(*ListRecordsResponse)(nil),  // 18: ziwei.v1.ListRecordsResponse
	(*CreateRecordRequest)(nil),  // 19: ziwei.v1.CreateRecordRequest
	(*CreateRecordResponse)(nil), // 20: ziwei.v1.CreateRecordResponse
	(*DeleteRecordRequest)(nil),  // 21: ziwei.v1.DeleteRecordRequest
	(*DeleteRecordResponse)(nil), // 22: ziwei.v1.DeleteRecordResponse
	(*Tag)(nil),                  // 23: ziwei.v1.Tag
	(*ListTagsRequest)(nil),      // 24: ziwei.v1.ListTagsRequest
	(*ListTagsResponse)(nil),     // 25: ziwei.v1.ListTagsResponse
	nil,                          // 26: ziwei.v1.CalculateResponse.PalacesEntry
	nil,                          // 27: ziwei.v1.CalculateResponse.DaYunPalaceTransformsEntry
	nil,                          // 28: ziwei.v1.CalculateResponse.LiuNianPalaceTransformsEntry
	nil,                          // 29: ziwei.v1.CalculateResponse.LiuYuePalaceTransformsEntry
	nil,                          // 30: ziwei.v1.CalculateResponse.LiuRiPalaceTransformsEntry
}
var file_ziwei_proto_depIdxs = []int32{
	26, // 0: ziwei.v1.CalculateResponse.palaces:type_name -> ziwei.v1.CalculateResponse.PalacesEntry
	8,  // 1: ziwei.v1.CalculateResponse.patterns:type_name -> ziwei.v1.PatternData
	9,  // 2: ziwei.v1.CalculateResponse.interpretation:type_name -> ziwei.v1.InterpretationData
	7,  // 3: ziwei.v1.CalculateResponse.da_yun:type_name -> ziwei.v1.DaYunData
	5,  // 4: ziwei.v1.CalculateResponse.liu_nian:type_name -> ziwei.v1.TemporalPalaceData
	5,  // 5: ziwei.v1.CalculateResponse.liu_yue:type_name -> ziwei.v1.TemporalPalaceData
	5,  // 6: ziwei.v1.CalculateResponse.liu_ri:type_name -> ziwei.v1.TemporalPalaceData
	7,  // 7: ziwei.v1.CalculateResponse.current_da_yun:type_name -> ziwei.v1.DaYunData
	27, // 8: ziwei.v1.CalculateResponse.da_yun_palace_transforms:type_name -> ziwei.v1.CalculateResponse.DaYunPalaceTransformsEntry
	28, // 9: ziwei.v1.CalculateResponse.liu_nian_palace_transforms:type_name -> ziwei.v1.CalculateResponse.LiuNianPalaceTransformsEntry
	29, // 10: ziwei.v1.CalculateResponse.liu_yue_palace_transforms:type_name -> ziwei.v1.CalculateResponse.LiuYuePalaceTransformsEntry
	30, // 11: ziwei.v1.CalculateResponse.liu_ri_palace_transforms:type_name -> ziwei.v1.CalculateResponse.LiuRiPalaceTransformsEntry
	3,  // 12: ziwei.v1.PalaceData.star_details:type_name -> ziwei.v1.PalaceStar
	4,  // 13: ziwei.v1.PalaceData.natal_transforms:type_name -> ziwei.v1.TransformData
	4,  // 14: ziwei.v1.PalaceData.liu_nian_transforms:type_name -> ziwei.v1.TransformData
	4,  // 15: ziwei.v1.PalaceData.liu_yue_transforms:type_name -> ziwei.v1.TransformData
	4,  // 16: ziwei.v1.PalaceData.liu_ri_transforms:type_name -> ziwei.v1.TransformData
	11, // 17: ziwei.v1.PalaceData.fly_hua:type_name -> ziwei.v1.FlyHuaAnalysis
	4,  // 18: ziwei.v1.PalaceTransformGroup.transforms:type_name -> ziwei.v1.TransformData
	4,  // 19: ziwei.v1.DaYunData.transforms:type_name -> ziwei.v1.TransformData
	14, // 20: ziwei.v1.InterpretationData.karmic_narrative:type_name -> ziwei.v1.KarmicStep
	15, // 21: ziwei.v1.InterpretationData.san_fang_diagnosis:type_name -> ziwei.v1.SanFangRole
	10, // 22: ziwei.v1.InterpretationData.star_details:type_name -> ziwei.v1.DeepStarAnalysis
	11, // 23: ziwei.v1.InterpretationData.origin_fly_hua:type_name -> ziwei.v1.FlyHuaAnalysis
	13, // 24: ziwei.v1.InterpretationData.temporal_resonance:type_name -> ziwei.v1.ResonancePoint
	12, // 25: ziwei.v1.FlyHuaAnalysis.stages:type_name -> ziwei.v1.FlyStage
	16, // 26: ziwei.v1.ListRecordsResponse.records:type_name -> ziwei.v1.BirthRecord
	16, // 27: ziwei.v1.CreateRecordResponse.record:type_name -> ziwei.v1.BirthRecord
	23, // 28: ziwei.v1.ListTagsResponse.tags:type_name -> ziwei.v1.Tag
	2,  // 29: ziwei.v1.CalculateResponse.PalacesEntry.value:type_name -> ziwei.v1.PalaceData
	6,  // 30: ziwei.v1.CalculateResponse.DaYunPalaceTransformsEntry.value:type_name -> ziwei.v1.PalaceTransformGroup
	6,  // 31: ziwei.v1.CalculateResponse.LiuNianPalaceTransformsEntry.value:type_name -> ziwei.v1.PalaceTransformGroup
	6,  // 32: ziwei.v1.CalculateResponse.LiuYuePalaceTransformsEntry.value:type_name -> ziwei.v1.PalaceTransformGroup
	6,  // 33: ziwei.v1.CalculateResponse.LiuRiPalaceTransformsEntry.value:type_name -> ziwei.v1.PalaceTransformGroup
	0,  // 34: ziwei.v1.ZiweiService.Calculate:input_type -> ziwei.v1.CalculateRequest
	17, // 35: ziwei.v1.ZiweiService.ListRecords:input_type -> ziwei.v1.ListRecordsRequest
	19, // 36: ziwei.v1.ZiweiService.CreateRecord:input_type -> ziwei.v1.CreateRecordRequest
	21, // 37: ziwei.v1.ZiweiService.DeleteRecord:input_type -> ziwei.v1.DeleteRecordRequest
	24, // 38: ziwei.v1.ZiweiService.ListTags:input_type -> ziwei.v1.ListTagsRequest
	1,  // 39: ziwei.v1.ZiweiService.Calculate:output_type -> ziwei.v1.CalculateResponse
	18, // 40: ziwei.v1.ZiweiService.ListRecords:output_type -> ziwei.v1.ListRecordsResponse
	20, // 41: ziwei.v1.ZiweiService.CreateRecord:output_type -> ziwei.v1.CreateRecordResponse
	22, // 42: ziwei.v1.ZiweiService.DeleteRecord:output_type -> ziwei.v1.DeleteRecordResponse
	25, // 43: ziwei.v1.ZiweiService.ListTags:output_type -> ziwei.v1.ListTagsResponse
	39, // [39:44] is the sub-list for method output_type
	34, // [34:39] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_ziwei_proto_init() }
func file_ziwei_proto_init() {
	if File_ziwei_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ziwei_proto_rawDesc), len(file_ziwei_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ziwei_proto_goTypes,
		DependencyIndexes: file_ziwei_proto_depIdxs,
		MessageInfos:      file_ziwei_proto_msgTypes,
	}.Build()
	File_ziwei_proto = out.File
	file_ziwei_proto_goTypes = nil
	file_ziwei_proto_depIdxs = nil
}
